services:

  # MongoDB database
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db/mongodb/
    networks:
      - mongo-express__mongodb
      - photography-backend__mongodb

  # MongoDB database client
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_SITE_BASEURL: /mongo-express
      ME_CONFIG_BASICAUTH: false
    networks:
      - nginx__mongo-express
      - mongo-express__mongodb
    depends_on:
      - mongodb
    restart: always

  # Photography backend
  photography-backend:
    build:
      context: ./photography/backend
      dockerfile: ./Dockerfile
    container_name: photography-backend
    ports:
      - "5001:5001"
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017
      IMAGES_VOLUME: /data/images/photography
      BASE_PATH: /photography/api
      PORT: 5001
    volumes:
      - ./photography/images:/data/images/photography
    networks:
      - nginx__photography-backend
      - photography-backend__mongodb
    depends_on:
      - mongodb
    restart: always

  # Photography frontend
  photography-frontend:
    build: ./photography/frontend
    container_name: photography-frontend
    networks:
      - nginx__photography-frontend
    depends_on:
      - photography-backend
    restart: always
    # stdin_open: true        # Equivalent to `-i` (interactive)
    # tty: true               # Equivalent to `-t` (pseudo-TTY)
    # command: /bin/sh        # or /bin/sh if Bash isn't installed
      
  # Landing page
  landing-page:
    build: ./landing
    container_name: landing-page
    networks:
      - nginx__landing-page
    restart: always
      
  # Keycloak authentication server
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
    networks:
      - nginx__keycloak
    restart: always

  # Reverse nginx proxy
  nginx-proxy:
    image: nginx:alpine-slim
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx__landing-page
      - nginx__mongo-express
      - nginx__photography-backend
      - nginx__photography-frontend
      - nginx__keycloak
    depends_on:
      - landing-page
      - mongo-express
      - photography-backend
      - photography-frontend
      - keycloak

volumes:
  mongodb:

networks:
  nginx__landing-page:
  nginx__mongo-express:
  mongo-express__mongodb:
  nginx__photography-backend:
  nginx__photography-frontend:
  photography-backend__mongodb:
  nginx__keycloak:
