services:
  landing-page:
    build: ./landing
    container_name: landing-page
    restart: always

  nginx-proxy:
    image: nginx:alpine-slim
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - landing-page
